<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="/"><?php echo $this->dxConfig()->getOptions()->getProjectName()?></a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li><a href="/">Home</a></li>
					<?php if(!$this->zfcUserIdentity()):?>
						<li><a href="/login">Login</a></li>
					<?php endif;?>
					<?php if($this->zfcUserIdentity()):?>
						<li><a href="/account">Account</a></li>
					<?php endif;?>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Links<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a target="_blank" href="http://claremontdesign.com">Claremont Design</a></li>
							<li><a target="_blank" href="http://labs.madayaw.com">MadLabs</a></li>
							<li class="divider"></li>
							<li><a target="_blank" href="http://framework.zend.com/learn">ZF2 Docs</a></li>
							<li><a target="_blank" href="http://framework.zend.com/zf2">ZF2 Dev Portal</a></li>
							<li><a target="_blank" href="http://modules.zendframework.com/">ZF2 Modules</a></li>
							<li><a target="_blank" href="https://github.com/zendframework/zf2">ZF2 on GitHub</a></li>
							<li><a target="_blank" href="http://www.phpdoc.org/docs/latest/index.html">phpDocumentor</a></li>
							<li class="divider"></li>
							<li><a target="_blank" href="http://docs.doctrine-project.org/en/latest/reference/working-with-associations.html">Doctrine Entity - Association</a></li>
							<li><a target="_blank" href="http://docs.doctrine-project.org/en/2.0.x/reference/tools.html">Doctrine Tools</a></li>
							<li><a target="_blank" href="http://www.zendcasts.com/many-to-many-with-doctrine-2/2011/03/">Doctrine - ZendCast</a></li>
							<li><a target="_blank" href="http://gediminasm.org/article/tree-nestedset-behavior-extension-for-doctrine-2">GedMo Documents</a></li>
						</ul>
					</li>


				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
</div>