<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$params = $this->params;
$route = $this->route;
?>








<?php if ($this->pageCount): ?>
	<div class="row">
		<div class="span3">
			<div class="pagination">
				<ul>

					<li><span>
							Event <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> of <?php echo $this->totalItemCount; ?>
						</span></li>
				</ul>
			</div>
		</div>
		<div class="span6">
			<div class="pagination pagination-right">
				<ul>
					<!-- Previous page link -->
					<?php if (isset($this->previous)): ?>
						<?php $params['page'] = $this->previous; ?>
						<li><a title="Previous Page" href="<?php echo $this->dxHtml()->url($route, $params); ?>">
								&laquo;
							</a></li>
					<?php else: ?>
						<li class="disabled"><a href="#">&laquo;</a></li>
					<?php endif; ?>




					<!-- Next page link -->
					<?php if (isset($this->next)): ?>
						<?php $params['page'] = $this->next; ?>
						<li><a title="Next page" href="<?php echo $this->dxHtml()->url($route, $params); ?>">
								&raquo;
							</a></li>
					<?php else: ?>
						<li class="disabled"><a href="#">&raquo;</a></li>
					<?php endif; ?>

				</ul>
			</div>
		</div>

	</div>



<?php endif; ?>

