<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
		<?php echo $this->partial('head.phtml') ?>
    </head>
    <body class="<?php echo $this->dxHtml()->getBodyClass()?>">
		<?php echo $this->partial('header.phtml') ?>
		<?php echo $this->partial('nav.phtml') ?>
		<div class="container">
			<?php echo $this->dxBreadcrumb()->render()?>
			<?php echo $this->dxHtml()->getTitle() ? '<h1>' . $this->dxHtml()->getTitle() . '</h1>' : ''; ?>
			<?php echo $this->dxAlert()->render()?>
			<?php echo $this->content ?>
			<?php echo $this->partial('footer.phtml') ?>
		</div>
		<?php echo $this->partial('foot.phtml') ?>
    </body>
</html>
